### PR TITLE
Fixes itemDisplay and rating

### LINKED ISSUE #95: [Bug] addition of rating not working
**Describe the bug**
once a rating has been added the first time, any subsequent changes to the rating do not reflect in the backend.

**To Reproduce**
1. Create a new item
2. Rate the item
3. Try rating it again
4. See the database (no changes after first addition)

**Expected behavior**
Rating should change each time it is modified

### LINKED ISSUE #96: [Bug] items not displaying without hard refresh
**Describe the bug**
When you switch to a different category for the first time, the items do not display. A hard refresh (ctrl + shift + r) needs to be done in order to display them.

**To Reproduce**
1. Go to any category
2. Add an item
3. Go to another category
4. Hard refresh (ctrl + shift + r)
5. Navigate to the previous category (in which you added a new item)
6. The item does not show up

**Expected behavior**
The items should show up irrespective of when they are added, and whether the page has been hard refreshed

### PR DESCRIPTION
**Pull request by gsc2001**
- [Fix] Items display on tab change
- [Fix] Rating working

This fixes #95 and fixes #96

### CODE REVIEW

**Comment by gsc2001** [comment]
Dont merge right now, trying to add a loading state while items are fetched

**Comment by gsc2001** [comment]
Done now!

File: frontend/src/components/AddItemSheet.vue [hunk 1]
```diff
@@ -32,68 +31,68 @@
...
-    return {
-      overlay: false,
-      formData: {}
-    }
-  },
-  methods: {
-    submit1: function (data) {
-      // get back data
-      this.formData = JSON.parse(data)
+    name: "AddPostSheetTemp",
```
Comment (Pk13055) [inline frontend/src/components/AddItemSheet.vue:38]: Shouldn’t this name be changed?
