### PR TITLE
[Fixes] Fab and added separate forms for creating post

### LINKED ISSUE #55: [Bug] Add Post button disappears
The FAB for add post disappears on navigating to any of the category pages.

FAB Present on homepage:
Screenshot from 2020-06-25 17-46-25

FAB **NOT** present on anime page:
Screenshot from 2020-06-25 17-47-37

## Details

- Using `docker-compose`
- Latest `template` branch

### PR DESCRIPTION
**Pull request by Megha-Bose**
Fixes #55

### CODE REVIEW

File: frontend/src/components/FloatingButton.vue [hunk 1]
```diff
@@ -18,8 +18,8 @@
 
         <div v-else>
           <div v-for="item in categories" :key="item.title">
-            <v-tooltip left>
-              <template v-slot:activator="{ on, attrs }">
+            <!-- <v-tooltip left>
+              <template #activator="{ on, attrs }"> -->
```
Comment (Pk13055) [inline frontend/src/components/FloatingButton.vue:22]: Why did you comment this out? If it's not relevant just delete this part.

Comment (Megha-Bose) [reply frontend/src/components/FloatingButton.vue:22]: Okay, I will do that.
